# Generated by Django 4.2.9 on 2024-01-28 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 28, 7, 25, 42, 644355, tzinfo=datetime.timezone.utc))),
                ('intro', models.TextField()),
                ('boldi', models.TextField()),
                ('paraf', models.TextField()),
                ('paraf1', models.TextField()),
                ('paraf2', models.TextField()),
                ('paraf3', models.TextField()),
                ('boldi2', models.TextField()),
                ('paraf4', models.TextField()),
                ('paraf5', models.TextField()),
                ('paraf6', models.TextField()),
                ('paraf7', models.TextField()),
                ('boldi3', models.TextField()),
                ('paraf8', models.TextField()),
                ('paraf9', models.TextField()),
                ('paraf10', models.TextField()),
                ('paraf11', models.TextField()),
                ('boldi4', models.TextField()),
                ('paraf12', models.TextField()),
                ('paraf13', models.TextField()),
                ('paraf14', models.TextField()),
                ('paraf15', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('bolds', models.TextField()),
                ('paras', models.TextField()),
                ('paras1', models.TextField()),
                ('paras2', models.TextField()),
                ('paras3', models.TextField()),
                ('bolds2', models.TextField()),
                ('paras4', models.TextField()),
                ('paras5', models.TextField()),
                ('paras6', models.TextField()),
                ('paras7', models.TextField()),
                ('bolds3', models.TextField()),
                ('paras8', models.TextField()),
                ('paras9', models.TextField()),
                ('paras10', models.TextField()),
                ('paras11', models.TextField()),
                ('bolds4', models.TextField()),
                ('paras12', models.TextField()),
                ('paras13', models.TextField()),
                ('paras14', models.TextField()),
                ('paras15', models.TextField()),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
