# Generated by Django 4.2.9 on 2024-01-28 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='boldi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='boldi2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='boldi3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='boldi4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='bolds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='bolds2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='bolds3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='bolds4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 28, 7, 29, 2, 22195, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paraf9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='paras9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
