# Generated by Django 4.2.9 on 2024-01-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_alter_blog_post_boldi_alter_blog_post_boldi2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
