# Generated by Django 4.2.9 on 2024-01-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0003_alter_blog_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='image2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
