# Generated by Django 4.1.3 on 2024-02-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0004_blog_post_image2_alter_blog_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='outro',
            field=models.TextField(default='~ KEEP TWINKLING ~'),
        ),
    ]
