# Generated by Django 4.1.3 on 2024-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0005_blog_post_outro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='outro',
            field=models.TextField(default='~ 🌟 KEEP TWINKLING 🌟 ~'),
        ),
    ]
