# Generated by Django 4.1.3 on 2024-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0006_alter_blog_post_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='category',
            field=models.CharField(default='Education', max_length=250),
        ),
    ]
